import { Product } from "@/types/product";

export const mockProducts: Product[] = [
  {
    id: "1",
    name: "Premium Photo Frame",
    description: "High-quality wooden frame perfect for cherished memories. Available in multiple sizes.",
    basePrice: 1500,
    category: "frames",
    images: ["/placeholder.svg"],
    customizationOptions: [
      {
        id: "size",
        type: "select",
        label: "Frame Size",
        required: true,
        options: ["8x10", "11x14", "16x20"],
        priceImpact: 0,
      },
      {
        id: "message",
        type: "text",
        label: "Custom Engraving (Optional)",
        required: false,
        priceImpact: 200,
      },
    ],
    stockQuantity: 50,
    isFeatured: true,
  },
  {
    id: "2",
    name: "Custom T-Shirt",
    description: "Premium cotton t-shirts with your custom design or text. Perfect for events or personal branding.",
    basePrice: 800,
    category: "apparel",
    images: ["/placeholder.svg"],
    customizationOptions: [
      {
        id: "size",
        type: "select",
        label: "Size",
        required: true,
        options: ["S", "M", "L", "XL", "XXL"],
      },
      {
        id: "design",
        type: "image",
        label: "Upload Your Design",
        required: true,
        priceImpact: 0,
      },
      {
        id: "text",
        type: "text",
        label: "Custom Text (Optional)",
        required: false,
      },
    ],
    stockQuantity: 100,
    isFeatured: true,
  },
  {
    id: "3",
    name: "Personalized Mug",
    description: "Ceramic coffee mug with your photos, text, or designs. Dishwasher and microwave safe.",
    basePrice: 600,
    category: "mugs",
    images: ["/placeholder.svg"],
    customizationOptions: [
      {
        id: "design",
        type: "image",
        label: "Upload Photo/Design",
        required: true,
      },
      {
        id: "text",
        type: "text",
        label: "Add Text",
        required: false,
      },
    ],
    stockQuantity: 75,
    isFeatured: true,
  },
  {
    id: "4",
    name: "Christian Wall Art",
    description: "Beautiful scripture-based wall art to inspire faith in your home or office.",
    basePrice: 1200,
    category: "christian",
    images: ["/placeholder.svg"],
    customizationOptions: [
      {
        id: "verse",
        type: "select",
        label: "Choose Scripture",
        required: true,
        options: [
          "Jeremiah 29:11",
          "Philippians 4:13",
          "Proverbs 3:5-6",
          "Psalm 23:1",
          "Custom Verse",
        ],
      },
      {
        id: "size",
        type: "select",
        label: "Size",
        required: true,
        options: ["12x16", "16x20", "20x24"],
        priceImpact: 300,
      },
    ],
    stockQuantity: 30,
    isFeatured: false,
  },
  {
    id: "5",
    name: "Branded Gift Set",
    description: "Complete corporate gift set including notebook, pen, and branded items.",
    basePrice: 2500,
    category: "gifts",
    images: ["/placeholder.svg"],
    customizationOptions: [
      {
        id: "logo",
        type: "image",
        label: "Company Logo",
        required: true,
      },
      {
        id: "quantity",
        type: "select",
        label: "Quantity",
        required: true,
        options: ["10 sets", "25 sets", "50 sets", "100 sets"],
        priceImpact: 0,
      },
    ],
    stockQuantity: 20,
    isFeatured: false,
  },
  {
    id: "6",
    name: "Custom Tumbler",
    description: "Stainless steel tumbler with vacuum insulation. Keeps drinks hot or cold for hours.",
    basePrice: 1000,
    category: "mugs",
    images: ["/placeholder.svg"],
    customizationOptions: [
      {
        id: "color",
        type: "select",
        label: "Tumbler Color",
        required: true,
        options: ["Black", "White", "Silver", "Rose Gold"],
      },
      {
        id: "design",
        type: "image",
        label: "Upload Design",
        required: false,
        priceImpact: 200,
      },
    ],
    stockQuantity: 60,
    isFeatured: false,
  },
];
